config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :chains
  resources :equipment
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/active.rb
class Active < ApplicationRecord
  belongs_to :chain
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign.rb
class Assign < ApplicationRecord
  belongs_to :chain
  belongs_to :equipment
end

app/models/chain.rb
class Chain < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :risk, presence: true
  has_many :actives
  has_many :users, through: :actives
  has_many :assigns
  has_many :equipment, through: :assigns
  has_many :services
  has_many :providers, through: :services
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :provider
end

app/models/equipment.rb
class Equipment < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :name, presence: true
  validates :size, presence: true
  validates :unit, presence: true
  has_many :assigns
  has_many :chains, through: :assigns
end

app/models/provider.rb
class Provider < ApplicationRecord
  has_many :services
  has_many :chains, through: :services
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
end

app/models/request_detail.rb
class RequestDetail < ApplicationRecord
  belongs_to :request
  belongs_to :chain
  belongs_to :equipment
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :chain
  belongs_to :provider
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :actives
  has_many :chains, through: :actives
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address, :phone, :name, :number, :fax])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:address, :phone, :name, :number, :fax])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/chains_controller.rb
class ChainsController < ApplicationController
  def index
    @chains = policy_scope(Chain).order(created_at: :desc)
  end

  def show
  end

  def new
    @chain = Chain.new
    authorize @chain
  end

  def create
    @chain = Chain.new(chain_params)
    authorize @chain
    if @chain.save
      redirect_to chains_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def chain_params
    params.require(:chain).permit(:name, :risk, :photo)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController

  def index
    @equipments = policy_scope(Equipment).order(created_at: :desc)
  end

  def show
  end

  def new
    @equipment = Equipment.new
    authorize @equipment
  end

  def create
    @equipment = Equipment.new(equipment_params)
    authorize @equipment
    if @equipment.save
      redirect_to equipment_index_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end
private
  def equipment_params
    params.require(:equipment).permit(:name, :size, :unit, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chains/index.html.erb
<div class="back-chains">
  <div class="row">
    <% @chains.each do |chain| %>
    <div class="col-xs-12 col-md-4 chain-container">
      <div class="card chain_card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path chain.photo, crop: :fill %>')">
        <div class="chain-description">
          <div class="chain-title">
            <%= chain.name %>
          </div>
          <% if chain.risk == "DND" %>
          <div class="chain-risk safe">
            <% else %>
            <div class="chain-risk unsafe">
              <% end %>
              <%= chain.risk.to_s  %>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class="chain-add">
      <%= link_to "Créer une nouvelle filière", new_chain_path, class: "btn btn-primary" %>
    </div>
  </div>

app/views/chains/new.html.erb
<h1>Créer une nouvelle filière</h1>

<%= simple_form_for @chain do |f| %>
<%= f.input :name %>
<%= f.input :risk, as: :radio_buttons, collection: [['Déchets Dangereux', 'DD'], ['Déchets Non Dangereux', 'DND']] %>
<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/equipment/index.html.erb
<div class="back-equip">
<h1> Liste des équipements enregistrés </h1>
<div class="row">
  <% @equipments.each do |equipment| %>
  <div class="col-xs-12 col-md-4">
    <div class="card equip_card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path equipment.photo, crop: :fill %>')">
      <div class="equip-description">
        <div class="equip-title">
          <%= equipment.name %>
        </div>
        <div class="equip-size">
          <%= equipment.size.to_s %>
        </div>
        <div class="equip-unit">
          <%= equipment.unit  %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= link_to "Créer un nouvel equipement", new_equipment_path, class: "btn btn-primary" %>
</div>

app/views/equipment/new.html.erb
<%= simple_form_for @equipment do |f| %>
  <%= f.input :name %>
  <%= f.input :size %>
  <%= f.input :unit %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Environment Platform</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Bienvenue sur le portail de gestion des produits usagés</h1>
<p>Vous souhaitez : </p>

<%= link_to "Accéder à la page des filières", chains_path, class: "btn btn-primary" %>
<%= link_to "Accéder à la page des équipements", equipment_index_path, class: "btn btn-primary" %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "environment.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "historique", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "filières", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "equipements", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "home", root_path %></li>
        <li><%= link_to "filières", chains_path %></li>
        <li><%= link_to "Equipements", equipment_index_path %></li>
      </ul>
    </div>
  </div>
</div>